### ISSUE TITLE
Error when choosing GetHighestPemdas 

### ISSUE THREAD

**Issue by YordanPavlov** [dmanning23/Equationator#4]
Hi there,
I come across your project while doing something similar. I noticed something strange when you are choosing the highest pemda in 

`private BaseNode GetHighestPemdas()`

my suspicious were confirmed when I noticed that you have a wrong test:

https://github.com/dmanning23/Equationator/blob/5ae1ed9c14a3d9c200d7b13413695e252909b8c3/Equationator/Equationator.Tests/Test.cs#L182

should be 0.5 and not -2.5. 

I believe that on choosing the next highest pemda you should get addition over subtraction. Also choose the 'right most' one first. The cycle you are doing in GetHighestPemdas effectively chooses the 'left most' first and treats it as if the rest have brackets around them.

Cheers, hope this helps!

**Comment by dmanning23** [comment]
Yup, never noticed that, thank you for finding it!

Fixed it in this checkin, and added a couple more unit tests:
ae2f5f66911b463e6ccd96e964d7393e46d12a28
